### ISSUE TITLE
Autotrim not working via QSHELL

### ISSUE THREAD

**Issue by DannyRidgway** [php/pecl-database-ibm_db2#17]
_PHP Version: 7.2.15
Module Version: 2.0.6-zs1_

On SQL inserts and updates string fields are automatically trimmed if over the field length. This is not the case via QShell though. This is using normal ASCII characters. No UTF-8 characters used. Any extra characters are discarded (ASCII or UTF-8) no errors or warnings produced.

I have the same script running via the HTTP server and QShell using the php-cli.

PHP and all module ini files are the same when going through the HTTP server or QShell. The job is the same running the HTTP instance and QShell.

The database file is compiled using DDS and is flagged with CCSID(1208)
Field is defined as so.
```
CIMSTKD      140A         TEXT('Description')
                          COLHDG('Desc')   
                          VARLEN(35)               
```

Running via QShell has the following error.
`db2_execute(): Statement Execute Failed. Value for column or variable CIMSTKD too long.`

Is the autotrim even intended functionality? Logically it should fail on insert.

On a side note do you know what's happening with this bug? I reported it a while a go but nothing seems to have happened with it.
https://bugs.php.net/bug.php?id=76586

**Comment by kadler** [comment]
Inserts and updates should only allow trimming if the trimmed data is blank padded (and then I'd expect a warning). If the data is non-whitespace data, I'd expect an error on insert/update.

**Comment by DannyRidgway** [comment]
Yeah that's odd then.

I can confirm running it through the HTTP server just trims the end off regardless of what's after the field length in it. ASCII or UTF-8. (Not checked to see if it keeps double byte or more characters intact)

We have another 2 servers that have a slightly lower DB2 PTF version and those allow full character strings to be trimmed via HTTP or QShell.

**Comment by kadler** [comment]
It's possible that the trimming is being done by the PHP code before it gets to Db2, which could explain the difference.

**Comment by DannyRidgway** [comment]
Not that I'm aware of. I'm directly calling db2_prepare, db2_bind_param, and db2_execute. In my example the field is treated as DB2_CHAR

Unless those module functions have been modified by Zend.

**Comment by NattyNarwhal** [comment]
It's possible; Zend had some patches related to char trimming that AFAIK were eventually merged back upstream.

**Comment by DannyRidgway** [comment]
Ok thanks. Just wondered if you had any ideas.
