### ISSUE TITLE
pconnect doesn't check for valid password after a connection has been made

### ISSUE THREAD

**Issue by NattyNarwhal** [php/pecl-database-ibm_db2#18]
A customer informed us of an issue where `db2_pconnect` doesn't seem to verify the password after the persistent connection has been established, and they were concerned about this behaviour.

Reproduction:

```php
<?php


// test pconnect

$start = microtime(true);

echo "about to connect<BR>";
// do this the first time
$conn = db2_pconnect('*LOCAL', 'user', 'good password');
// then the second time
//$conn = db2_pconnect('*LOCAL', 'user', 'bad password');
var_dump($conn);
echo "any errors: " . db2_conn_errormsg() . '<BR>';

//$sql = "select * from qiws.qcustcdt where LSTNAM = 'Henning'";//?";

$sql = "select * from qiws.qcustcdt where LSTNAM = ?";//?";

echo "<BR>about to prepare<BR>";
$stmt = db2_prepare($conn, $sql);
var_dump($stmt);
echo "any errors: " . db2_stmt_errormsg() . '<BR>';

$lstnam = 'Henning';


echo "<BR>about to bind<BR>";
$result = db2_bind_param($stmt, 1, 'lstnam', DB2_PARAM_IN);//conn, $sql);
var_dump($result);
echo "any errors: " . db2_stmt_errormsg() . '<BR>';



echo "<BR>about to exec<BR>";
$result = db2_execute($stmt);
var_dump($result);
echo "any errors: " . db2_stmt_errormsg() . '<BR>';

echo "<BR>about to fetch<BR>";
$row = db2_fetch_assoc($stmt);
var_dump($row);
echo "any errors: " . db2_stmt_errormsg() . '<BR>';

$stmt = "";

$duration = microtime(true) - $start;

echo "<BR>Duration: {$duration} seconds.<BR>";
```

Alan looked into this and noted [only the UID and database](https://github.com/php/pecl-database-ibm_db2/blob/master/ibm_db2.c#L2356-L2363) are used in the hash for a persistent connection, and connections function . However, specifying `i5_check_pconnect` to 4 does force the connection to fail as the user thinks it should. [The path for level 4](https://github.com/php/pecl-database-ibm_db2/blob/master/ibm_db2.c#L2381-L2397) involves executing a dummy statement (previous levels merely query the DB or create a handle). Not sure why it'd fail the connection only then; I would think that a query would behave the same as it would later in the program. We're proposing setting it to 4 as a workaround for that customer and see if it's solving it.

I'd like to know if this is something worth fixing (i.e. is it actually safe to assume, and it's NOTABUG?); two workarounds I can think of off-hand are either store a (hashed) password as part of the persistent connection hash, or eat the costs of connection init/teardown for a persistent connection before reusing one (as a level 5?).

**Comment by tessus** [comment]
This is strange, because I brought this up years ago and even provided a patch. It seems they have ignored me. I thought it would have been fixed by now. Oh, well. I gave up on trying to move something along with IBM.... especially now since I am no longer with IBM.

**Comment by tessus** [comment]
I don't have the patch anymore, but I basically created a hash from the password and took a substr from that hash and added it to `hKey`.

**Comment by NattyNarwhal** [comment]
Shouldn't be too hard to recreate, I'll see what I can do tomorrow for a simple fix.

**Comment by NattyNarwhal** [comment]
Adjacent: The customer that reproduces the issue says the level 4 workaround works, but creates seemingly spurious spool file entries that look like this.

![image](https://user-images.githubusercontent.com/3161292/144664008-9c7caed0-f2f8-48f7-b65c-61596b954fda.png)

Me and Alan guess that it's this line:

https://github.com/php/pecl-database-ibm_db2/blob/master/ibm_db2.c#L2389

Why? The input length is provided using strlen, which may just result in 0, causing the above message, which results in `rc` no longer being `SQL_SUCCESS`, which triggers this:

https://github.com/php/pecl-database-ibm_db2/blob/master/ibm_db2.c#L2413-L2416

Which marks the connection as dead. It works by accident... Probably another separate issue to fix.

**Comment by tessus** [comment]
Unfortuntely I can't speak to that. I haven't had access to an AS/400 for a long time and most of the PASE specific code was added after the PHP driver was taken off our hands. Someone decided back then that the driver (and client code) will no longer be maintained in the Toronto lab.

**Comment by NattyNarwhal** [comment]
This is almost certainly the work of Tony, who added a bunch of those ad-hoc PASE specific features long after. I think the fix for this is trivial, so I'll make that.

**Comment by NattyNarwhal** [comment]
I suspect we don't need to hash the password:

* PDO does so for all drivers; doesn't hash (see the `spprintf`) https://github.com/php/php-src/blob/master/ext/pdo/pdo_dbh.c#L293-L360
* Procedural ODBC doesn't bother; _also includes the connection options which is a good idea_ https://github.com/php/php-src/blob/master/ext/odbc/php_odbc.c#L2252
* Postgres has the password in connection string, doesn't bother https://github.com/php/php-src/blob/master/ext/pgsql/pgsql.c#L643-L655

I haven't found where OCI8 or the MySQL extensions put them.

The hash key is invisible to user applications, so I don't think there's any harm? Of course, there's the situation that the ecosystem is wrong, but that's something that should be dealt with by everyone if that's the case then.

**Comment by tessus** [comment]
I am not so sure that I like the fact that the password is available in clear text in memory. We don't need a cryptagraphic hash function. Most of the time only one user/password combination is used in web applications.

This is also the reason why I only used a sub string of the hash and not the entire hash back then. e.g. CRC32 is more than enough.

**Comment by praveen-db2** [comment]
@NattyNarwhal can we close if its addressed ?

**Comment by NattyNarwhal** [comment]
The PR for it is still open; I'm tempted to merge it (and fix this) tomorrow if there are no complaints.
