### ISSUE TITLE
version 2.1.6 will not install with pecl, missing manifest

### ISSUE THREAD

**Issue by ciscon** [php/pecl-database-ibm_db2#28]
downloading ibm_db2-2.1.6.tgz ...
Starting to download ibm_db2-2.1.6.tgz (191,956 bytes)
.........................................done: 191,956 bytes
ERROR: bad md5sum for file /tmp/pear/temp/ibm_db2/php_ibm_db2.h

**Comment by ThePrez** [comment]
Thanks for reporting! We'll get that fixed up

**Comment by dlorenzomop** [comment]
Hello, yes, same issue ... we use it also for a production application, if you can correct it quickly, it will be super  ... thanks ;-)

**Comment by RafaelMansilha** [comment]
Just had the same problem here, I get a older version just to continue work

`pecl install ibm_db2-2.1.5`

**Comment by NattyNarwhal** [comment]
We've just pushed 2.1.7 to PECL, which should resolve this.
