### ISSUE TITLE
SQL_BOOLEAN support

### ISSUE THREAD

**Issue by NattyNarwhal** [php/pecl-database-ibm_db2#56]
Someone requested support for this, I believe it's in 7.4+.

Roadmap:

* Shims to ensure it still builds on older versions of the OS
* Identify if LUW supports it
* Add support
* Tests, detect if we're on on i 7.4+

**Comment by kadler** [comment]
BOOLEAN is 7.5+. FYI, they reassigned SQL_DATALINK as SQL_BOOLEAN for numeric compatibility w/ LUW.

**Comment by NattyNarwhal** [comment]
This is impossible to implement in `db2_result` (and for that matter, `odbc_result`) without changing the API so that `false` isn't an error. It semantically sucks, but it's a major breaking change.

Binding might be possible for parameters, but column binding seems really stringy.

That said, I think it might be possible to introduce into PDO_IBM, since PDO supports booleans and unlike PDO_ODBC, isn't just binding strings only.
